name: ${project.name}
version: ${project.version}
author: Luck
main: me.lucko.extracontexts.ExtraContextsPlugin
depend: [LuckPerms]
softdepend: [WorldGuard, PlaceholderAPI, Towny]
api-version: 1.13

commands:
  extracontexts-reload:
    description: Reloads the configuration
    permission: extracontexts.reload
    usage: /extracontexts-reload